<a href="https://colab.research.google.com/github/BahruzHuseynov/Portfolio/blob/main/TensorFlow2_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple Linear Regression (y = mx + b)

<img src = "https://miro.medium.com/v2/resize:fit:816/1*c4k8fC6jZX6pL7AMJegwPg.png" width = "500">

### Test 1

In [88]:
import numpy as np

import tensorflow as tf
from tensorflow import keras
from keras import Sequential, layers

In [79]:
X_train = np.array([-3, -1,  0, 1, 2, 3, 4])
y_train = np.array([-5, -3, -1, 1, 3, 5, 7])
X_test = np.array([-2, 5, -4 ])
y_test = np.array([-4, 9, -7])

In [80]:
# Model Building
model = Sequential([
    layers.Dense(1, input_shape=[1])
])
model.compile(optimizer='sgd', loss = 'mean_squared_error', metrics = ['mae'])
model.fit(X_train, y_train, epochs = 250, validation_data = (X_test, y_test))

Epoch 1/250
1/1 [==============================] - 0s 495ms/step - loss: 0.4909 - mae: 0.5257 - val_loss: 0.3051 - val_mae: 0.5278
Epoch 2/250
1/1 [==============================] - 0s 35ms/step - loss: 0.4823 - mae: 0.5240 - val_loss: 0.2916 - val_mae: 0.5133
Epoch 3/250
1/1 [==============================] - 0s 40ms/step - loss: 0.4741 - mae: 0.5222 - val_loss: 0.2793 - val_mae: 0.4997
Epoch 4/250
1/1 [==============================] - 0s 47ms/step - loss: 0.4663 - mae: 0.5202 - val_loss: 0.2682 - val_mae: 0.4867
Epoch 5/250
1/1 [==============================] - 0s 61ms/step - loss: 0.4587 - mae: 0.5183 - val_loss: 0.2581 - val_mae: 0.4745
Epoch 6/250
1/1 [==============================] - 0s 68ms/step - loss: 0.4515 - mae: 0.5163 - val_loss: 0.2489 - val_mae: 0.4629
Epoch 7/250
1/1 [==============================] - 0s 66ms/step - loss: 0.4445 - mae: 0.5142 - val_loss: 0.2406 - val_mae: 0.4518
Epoch 8/250
1/1 [==============================] - 0s 71ms/step - loss: 0.4377 - mae: 0.5

In [87]:
# Predictions
preds = model.predict(X_test)
print(preds[:, 0])
print(y_test)

1/1 [==============================] - 0s 38ms/step
[-4.0721087  8.36972   -7.626917 ]
[-4  9 -7]


### Test 2 - Approximately, y = 2x + 1

In [89]:
X_train = np.array([4, 5, 8, 9, 12, 20, 32, 84])
y_train = np.array([9, 10, 17, 19, 24, 40, 64, 170])
X_test = np.array([6, 10, 14, 24])
y_test = np.array([13, 21, 29, 49])

In [94]:
# Model Building
# Loss increases to INFINITY
model = Sequential([
    layers.Dense(1, input_shape=[1])
])
model.compile(optimizer='sgd', loss = 'mean_squared_error')
model.fit(X_train, y_train, epochs = 15)

Epoch 1/15
1/1 [==============================] - 1s 900ms/step - loss: 6322.0801
Epoch 2/15
1/1 [==============================] - 0s 10ms/step - loss: 2796809.0000
Epoch 3/15
1/1 [==============================] - 0s 11ms/step - loss: 1237342080.0000
Epoch 4/15
1/1 [==============================] - 0s 18ms/step - loss: 547415228416.0000
Epoch 5/15
1/1 [==============================] - 0s 11ms/step - loss: 242183189823488.0000
Epoch 6/15
1/1 [==============================] - 0s 9ms/step - loss: 107144771016851456.0000
Epoch 7/15
1/1 [==============================] - 0s 10ms/step - loss: 47402149694725423104.0000
Epoch 8/15
1/1 [==============================] - 0s 8ms/step - loss: 20971288636227797909504.0000
Epoch 9/15
1/1 [==============================] - 0s 10ms/step - loss: 9277951340882863943843840.0000
Epoch 10/15
1/1 [==============================] - 0s 9ms/step - loss: 4104678585727054184921956352.0000
Epoch 11/15
1/1 [==============================] - 0s 11ms/step - los

In [95]:
# Let's change the optimizer from SGD to ADAM
model = Sequential([
    layers.Dense(1, input_shape=[1])
])
model.compile(optimizer='adam', loss = 'mean_squared_error', metrics = ['mae'])
model.fit(X_train, y_train, epochs = 500, validation_data = (X_test, y_test))

Epoch 1/500
1/1 [==============================] - 1s 786ms/step - loss: 92.7713 - mae: 6.4587 - val_loss: 24.4143 - val_mae: 4.6064
Epoch 2/500
1/1 [==============================] - 0s 55ms/step - loss: 92.1215 - mae: 6.4359 - val_loss: 24.2570 - val_mae: 4.5919
Epoch 3/500
1/1 [==============================] - 0s 39ms/step - loss: 91.4741 - mae: 6.4132 - val_loss: 24.1003 - val_mae: 4.5774
Epoch 4/500
1/1 [==============================] - 0s 40ms/step - loss: 90.8291 - mae: 6.3904 - val_loss: 23.9442 - val_mae: 4.5629
Epoch 5/500
1/1 [==============================] - 0s 41ms/step - loss: 90.1865 - mae: 6.3677 - val_loss: 23.7886 - val_mae: 4.5484
Epoch 6/500
1/1 [==============================] - 0s 39ms/step - loss: 89.5464 - mae: 6.3450 - val_loss: 23.6336 - val_mae: 4.5339
Epoch 7/500
1/1 [==============================] - 0s 36ms/step - loss: 88.9088 - mae: 6.3222 - val_loss: 23.4791 - val_mae: 4.5195
Epoch 8/500
1/1 [==============================] - 0s 39ms/step - loss: 88.

In [97]:
# The result above is not satisfactory, too. We can use optimizers, losses from tensorflow
# Then play with the parameters
from keras.optimizers import Adam
from keras.losses import MeanSquaredError
from keras.metrics import MeanAbsoluteError

model = Sequential([
    layers.Dense(1, input_shape=[1])
])
model.compile(optimizer=Adam(learning_rate=0.1), loss = MeanSquaredError(), metrics = [MeanAbsoluteError()])
model.fit(X_train, y_train, epochs = 500, validation_data = (X_test, y_test))

Epoch 1/500
1/1 [==============================] - 2s 2s/step - loss: 14577.4482 - mean_absolute_error: 79.2903 - val_loss: 2893.7710 - val_mean_absolute_error: 48.3767
Epoch 2/500
1/1 [==============================] - 0s 35ms/step - loss: 13771.7285 - mean_absolute_error: 77.0153 - val_loss: 2724.6953 - val_mean_absolute_error: 46.9280
Epoch 3/500
1/1 [==============================] - 0s 34ms/step - loss: 12989.5781 - mean_absolute_error: 74.7422 - val_loss: 2560.9421 - val_mean_absolute_error: 45.4813
Epoch 4/500
1/1 [==============================] - 0s 35ms/step - loss: 12231.3701 - mean_absolute_error: 72.4724 - val_loss: 2402.5889 - val_mean_absolute_error: 44.0376
Epoch 5/500
1/1 [==============================] - 0s 34ms/step - loss: 11497.4717 - mean_absolute_error: 70.2073 - val_loss: 2249.6997 - val_mean_absolute_error: 42.5978
Epoch 6/500
1/1 [==============================] - 0s 34ms/step - loss: 10788.1846 - mean_absolute_error: 67.9484 - val_loss: 2102.3315 - val_mean_

In [98]:
model.get_weights() # k = 2.00252268, b = 0.94068134

[array([[2.0025268]], dtype=float32), array([0.94068134], dtype=float32)]

In [99]:
preds = model.predict(X_test)
preds[:, 0], y_test

1/1 [==============================] - 0s 45ms/step


(array([12.955842, 20.96595 , 28.976055, 49.001324], dtype=float32),
 array([13, 21, 29, 49]))

# Functional APIs

from tensorflow.keras.models import Model <br> <br>

inputs = Input(shape=(1,)) <br>
outputs = Dense(1)(inputs) <br>
model = Model(inputs=inputs, outputs=outputs)