<a href="https://colab.research.google.com/github/BahruzHuseynov/Portfolio/blob/main/YL_PyTorch_for_DL_and_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Youtube Learning - https://www.youtube.com/watch?v=V_xro1bcAuA <br>
Book or Website version - https://www.learnpytorch.io <br>
PyTorch (Get Started) - https://pytorch.org/get-started/locally/

# PyTorch fundamentals
#### https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
torch.__version__

'2.1.0+cu121'

In [2]:
!nvidia-smi # GPU properties

Wed Dec 27 12:24:07 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Introduction to Tensors

In [9]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [10]:
# Vector
vector = torch.tensor([2,-5, 10, 7])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector.numpy())

tensor([ 2, -5, 10,  7])
1
torch.Size([4])
[ 2 -5 10  7]


In [11]:
# Matrix
matrix = torch.tensor([[2,-5], [10, 7]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix.numpy())

tensor([[ 2, -5],
        [10,  7]])
2
torch.Size([2, 2])
[[ 2 -5]
 [10  7]]


In [15]:
# Tensor
t = torch.tensor([[[1,2,3],
                   [3,6,9],
                   [2,4,5]],
                  [[3,1,0],
                   [5,2,4],
                   [2,9,8]]])
print(t)
print(t.ndim)
print(t.shape)
print(t.numpy())

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[3, 1, 0],
         [5, 2, 4],
         [2, 9, 8]]])
3
torch.Size([2, 3, 3])
[[[1 2 3]
  [3 6 9]
  [2 4 5]]

 [[3 1 0]
  [5 2 4]
  [2 9 8]]]


In [17]:
# Random tensors
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

print("--------------------------")
# Random tensors
random_tensor = torch.rand(2, 5, 5)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.2183, 0.0756, 0.0957, 0.6715],
        [0.7134, 0.2548, 0.5851, 0.5372],
        [0.3945, 0.5560, 0.3816, 0.4261]])
2
torch.Size([3, 4])
--------------------------
tensor([[[0.7401, 0.9325, 0.9391, 0.6867, 0.5286],
         [0.4561, 0.2385, 0.5093, 0.4837, 0.9163],
         [0.4277, 0.5579, 0.5196, 0.1277, 0.6701],
         [0.3144, 0.1208, 0.1896, 0.6249, 0.7024],
         [0.3964, 0.7095, 0.1026, 0.1096, 0.9059]],

        [[0.9915, 0.8943, 0.8161, 0.4300, 0.9931],
         [0.3985, 0.4436, 0.5658, 0.3141, 0.5554],
         [0.8366, 0.7636, 0.1894, 0.7896, 0.4704],
         [0.6033, 0.1427, 0.3051, 0.2546, 0.1497],
         [0.4000, 0.3875, 0.8094, 0.2442, 0.3732]]])
3
torch.Size([2, 5, 5])


In [18]:
# Create a random tensor of size (224, 224, 3) like RGB
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
# Zeros and Ones
print(torch.zeros(2,2))
print(torch.ones(size = (3,4)))

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [24]:
# Data Type
t = torch.rand(size = (2,3))
print(t.dtype)
print(t)
print("-----------------------------------")
t = t.to(torch.int32)
print(t.dtype)
print(t)

torch.float32
tensor([[0.3792, 0.0935, 0.7146],
        [0.9970, 0.6730, 0.9901]])
-----------------------------------
torch.int32
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [26]:
# Range
rng = torch.arange(1, 5)
print(rng)
print("------------------------------")
rng = torch.arange(1, 10, 3)
print(rng)

tensor([1, 2, 3, 4])
------------------------------
tensor([1, 4, 7])


In [28]:
# Tensors like
three_zeros = torch.zeros_like(input = rng)
three_zeros

tensor([0, 0, 0])

### Manipulating tensors

In [31]:
# Tensor and Scalar
t = torch.tensor([5,10,3])
print(t+10) # torch.add(t, 10)
print("-------------------------")
print(t*10) # torch.mul(t, 10)
print("-------------------------")
print(t-10) # torch.subtract(t, 10)
print("-------------------------")
print(t//10)
print("-------------------------")
print(t/10) # torch.divide(t, 10)

tensor([15, 20, 13])
-------------------------
tensor([ 50, 100,  30])
-------------------------
tensor([-5,  0, -7])
-------------------------
tensor([0, 1, 0])
-------------------------
tensor([0.5000, 1.0000, 0.3000])


In [37]:
# Matrix multiplication
t = torch.tensor([1,2,3])

print(t*t)
print("-------------------------------")
print(torch.matmul(t, t))
print("-------------------------------")
print(t @ t)

tensor([1, 4, 9])
-------------------------------
tensor(14)
-------------------------------
tensor(14)


In [38]:
a = torch.tensor([[1,2],
                  [3,4]])

b = torch.tensor([[5,10,-8,0],
                  [9,7,5,-2]])
print(a @ b)

tensor([[23, 24,  2, -4],
        [51, 58, -4, -8]])


In [39]:
print(a.T) # Transpose
print(b.T)

tensor([[1, 3],
        [2, 4]])
tensor([[ 5,  9],
        [10,  7],
        [-8,  5],
        [ 0, -2]])


In [43]:
# Tensor aggregation (min, max, sum, mean)
x = torch.arange(0, 100, 10)
print(x)
print("----------------------")
print(torch.min(x), x.min())
print(torch.max(x), x.max())
print(torch.sum(x), x.sum())
print("----------------------")
x = x.type(torch.float32)
print(torch.mean(x), x.mean())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
----------------------
tensor(0) tensor(0)
tensor(90) tensor(90)
tensor(450) tensor(450)
----------------------
tensor(45.) tensor(45.)


In [44]:
print(x.argmin(), torch.argmin(x))
print(x.argmax(), torch.argmax(x))

tensor(0) tensor(0)
tensor(9) tensor(9)


In [45]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [46]:
# Reshaping
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [50]:
# Viewing
z = x.view(3, 3) # z will share the same memory with x
z, z.shape

# so, if a value (not a shape) in 'z' changes, it will change in the same manner in 'x'
z[0, 1] = 10
print(z, x, sep = "\n")

tensor([[ 1, 10,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])
tensor([ 1, 10,  3,  4,  5,  6,  7,  8,  9])


In [51]:
# Stacking
x_stacked = torch.stack([x,x,x]) # default dim = 0
x_stacked

tensor([[ 1, 10,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 10,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 10,  3,  4,  5,  6,  7,  8,  9]])

In [52]:
x_stacked = torch.stack([x,x,x], dim = 1)
x_stacked

tensor([[ 1,  1,  1],
        [10, 10, 10],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9]])

In [54]:
# Squeezing and Unsqueezing
# Squeezing removes all single dimensions
x = torch.rand(size = (3,1,2,1))
print(x)
print("------------------------------")
print(torch.squeeze(x))
print("------------------------------")
print(x.squeeze())

tensor([[[[0.3778],
          [0.2926]]],


        [[[0.9405],
          [0.8471]]],


        [[[0.0200],
          [0.9335]]]])
------------------------------
tensor([[0.3778, 0.2926],
        [0.9405, 0.8471],
        [0.0200, 0.9335]])
------------------------------
tensor([[0.3778, 0.2926],
        [0.9405, 0.8471],
        [0.0200, 0.9335]])


In [56]:
# Unsqueezing - adds a single dimension to a target tensor at a specific dimension
x = torch.rand(size = (3,2))
print(x)
print(x.unsqueeze(dim = 0))

tensor([[0.8811, 0.2285],
        [0.0855, 0.3737],
        [0.0982, 0.1435]])
tensor([[[0.8811, 0.2285],
         [0.0855, 0.3737],
         [0.0982, 0.1435]]])


In [58]:
# Permute
x = torch.rand(size = (2, 4, 3))
y = x.permute(2, 0, 1)
print(x.shape)
print(y.shape)
print("-----------------------------------")
print(x)
print(y)

torch.Size([2, 4, 3])
torch.Size([3, 2, 4])
-----------------------------------
tensor([[[0.2148, 0.1851, 0.5401],
         [0.0270, 0.7911, 0.7090],
         [0.2308, 0.5893, 0.4152],
         [0.1257, 0.8238, 0.9155]],

        [[0.8143, 0.0965, 0.4915],
         [0.2490, 0.1930, 0.2391],
         [0.2066, 0.7969, 0.3381],
         [0.3625, 0.0301, 0.8218]]])
tensor([[[0.2148, 0.0270, 0.2308, 0.1257],
         [0.8143, 0.2490, 0.2066, 0.3625]],

        [[0.1851, 0.7911, 0.5893, 0.8238],
         [0.0965, 0.1930, 0.7969, 0.0301]],

        [[0.5401, 0.7090, 0.4152, 0.9155],
         [0.4915, 0.2391, 0.3381, 0.8218]]])
