<a href="https://colab.research.google.com/github/BahruzHuseynov/Portfolio/blob/main/Medium/TensorFlow/Tf1_Basic_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

### tf.Variable (Can be modified)

In [2]:
print(tf.Variable([2, 3], dtype = tf.int32))

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>


In [5]:
# Note that 'dtype' must be mentioned. It is not the second parameter in the method
# The problem: After executing the cell, you will see "dtype" still equal to "int32"
tf.Variable([2, 3], tf.float32)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [6]:
# Additionally, the shape of the tensor is not changable with tf.Variable()
tf.Variable([1,2,3,4], shape=(2,2))

ValueError: In this `tf.Variable` creation, the initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).

### Other Data Types

In [9]:
print(tf.Variable([2, 3], dtype = tf.float32))
print(tf.Variable([1, 2, 3, 4, 5], dtype = tf.int32))
print(tf.Variable(3 + 2j, dtype = tf.complex64))
print(tf.Variable("TF", dtype = tf.string))

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>
<tf.Variable 'Variable:0' shape=() dtype=complex64, numpy=(3+2j)>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'TF'>


### tf.constant (Cannot be modified)

In [10]:
# No problem about "shape"
# Same problem about "dtype"
print(tf.constant([5, 8], dtype = tf.int32))
print(tf.constant([1, 2, 3, 4], shape = (2, 2)))
print(tf.constant(4, shape = (3, 2), dtype = tf.float32))

tf.Tensor([5 8], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4. 4.]
 [4. 4.]
 [4. 4.]], shape=(3, 2), dtype=float32)


### Math Operations

In [11]:
a = tf.Variable([[1, 2], [3, 4]])
b = tf.Variable([[1, 1], [1, 1]])
c = tf.Variable([[5], [3]])

In [13]:
print(a + b)
print(tf.add(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [14]:
print(a-b)
print(tf.subtract(a, b))

tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)


In [16]:
print(a @ b)
print(tf.matmul(a, b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [23]:
print(a / 2)
print(tf.divide(a, 2))

tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


In [21]:
print(tf.square(5))
print(tf.sqrt(16.0))
print(tf.reduce_sum(a))
print(tf.reduce_max(a))
print(tf.reduce_min(a))
print(tf.reduce_mean(a))

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


### Type Conversion

In [24]:
x = tf.Variable([2, 3], dtype = tf.float32)
x = tf.cast(x, tf.int32)
print(x)

tf.Tensor([2 3], shape=(2,), dtype=int32)


### Shape Operation and Tensor Manipulation

In [27]:
print(tf.shape(x))
print(tf.size(x))
print(tf.reshape(x, (1, 2)))

tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [28]:
arr = tf.Variable([[1, 2], [3, 4]])
print(tf.transpose(arr))

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [32]:
r = tf.Variable([[[1, 2], [3, 4]]])
print(tf.shape(r))
print(tf.squeeze(r))
print(tf.expand_dims(r, 1))

tf.Tensor([1 2 2], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[[1 2]
   [3 4]]]], shape=(1, 1, 2, 2), dtype=int32)


In [36]:
x = tf.Variable([[1, 3], [2, 4]])
print(tf.boolean_mask(x, x > 2))

tf.Tensor([3 4], shape=(2,), dtype=int32)
